CREATE TABLE EMPLEADOS (
	ID_EMPLE NUMBER(8,0) NOT NULL,
	NOMBRE VARCHAR2(50 BYTE),
	APELLIDOS VARCHAR2(100 BYTE),
	DNI VARCHAR2(10 BYTE),
	CONTRA VARCHAR2(50 BYTE) NOT NULL,
	BORRADO NUMBER(1,0),
	CONECTADO NUMBER(1,0)
);

ALTER TABLE EMPLEADOS ADD CONSTRAINT PK_EMPLEADOS PRIMARY KEY (ID_EMPLE);

CREATE TABLE PRODUCTOS_TIPO1 (
	ID NUMBER(8,0) NOT NULL,
	TIPO VARCHAR2(50 BYTE)
);

ALTER TABLE PRODUCTOS_TIPO1 ADD CONSTRAINT PK_PRODUCTOS_TIPO1 PRIMARY KEY (ID);

CREATE TABLE PRODUCTOS_TIPO2 (
	ID NUMBER(8,0) NOT NULL,
	TIPO VARCHAR2(50 BYTE),
	T1 NUMBER(1,0)
);

ALTER TABLE PRODUCTOS_TIPO2 ADD CONSTRAINT PK_PRODUCTOS_TIPO2 PRIMARY KEY (ID);
ALTER TABLE PRODUCTOS_TIPO2 ADD CONSTRAINT FK_T2_T1 FOREIGN KEY (T1) REFERENCES PRODUCTOS_TIPO1(ID);

CREATE TABLE PRODUCTOS (
	ID_PRODUCTO NUMBER(8,0) NOT NULL,
	NOMBRE_PRODUCTO VARCHAR2(100 BYTE),
	TIPO1 NUMBER(1,0),
	TIPO2 NUMBER(1,0),
	STOCK NUMBER(6,0),
	PRECIO NUMBER(6,2),
	BORRADO NUMBER(1,0),
	AVISADO NUMBER(1,0)
);

ALTER TABLE PRODUCTOS ADD CONSTRAINT PK_PRODUCTOS PRIMARY KEY (ID_PRODUCTO);
ALTER TABLE PRODUCTOS ADD CONSTRAINT FK_PRODUCTOS_T1 FOREIGN KEY (TIPO1) REFERENCES PRODUCTOS_TIPO1(ID);
ALTER TABLE PRODUCTOS ADD CONSTRAINT FK_PRODUCTOS_T2 FOREIGN KEY (TIPO2) REFERENCES PRODUCTOS_TIPO2(ID);

CREATE TABLE FORMAS_PAGO (
	ID_FPAGO NUMBER(8,0) NOT NULL,
	FORMA_PAGO VARCHAR2(50 BYTE)
);

ALTER TABLE FORMAS_PAGO ADD CONSTRAINT PK_FORMAS_PAGO PRIMARY KEY (ID_FPAGO);

CREATE TABLE PEDIDOS (
	ID_PEDIDO NUMBER(8,0) NOT NULL,
	REF_EMPLE NUMBER(8,0) NOT NULL,
	REF_CLIENTE VARCHAR2(100 BYTE) NULL,
	REF_PAGO NUMBER(8,0) NULL,
	TOTAL NUMBER (8,2),
	PAGADO NUMBER (1,0),
	FACTURADO NUMBER(1,0),
	FECHA_PEDIDO DATE
);

ALTER TABLE PEDIDOS ADD CONSTRAINT PK_PEDIDOS PRIMARY KEY (ID_PEDIDO);
ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS_EMPLE FOREIGN KEY (REF_EMPLE) REFERENCES EMPLEADOS(ID_EMPLE);
ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS_PAGO FOREIGN KEY (REF_PAGO) REFERENCES FORMAS_PAGO(ID_FPAGO);

CREATE TABLE PEDIDOS_PRODUCTOS (
	ID_PEDIDO_PRODUC NUMBER(8,0) NOT NULL,
	REF_PEDIDO NUMBER(8,0) NOT NULL,
	REF_PRODUCTO NUMBER(8,0) NOT NULL,
	CANTIDAD NUMBER(4,0),
	PRECIO NUMBER(6,2)
);

ALTER TABLE PEDIDOS_PRODUCTOS ADD CONSTRAINT PK_PEDIDOS_RRODUCTOS PRIMARY KEY (ID_PEDIDO_PRODUC);
ALTER TABLE PEDIDOS_PRODUCTOS ADD CONSTRAINT FK_PEDIDPRODUC_PEDID FOREIGN KEY (REF_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO);
ALTER TABLE PEDIDOS_PRODUCTOS ADD CONSTRAINT FK_PEDIDPRODUC_PRODUC FOREIGN KEY (REF_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO);