CREATE TABLE EMPLEADOS (
	ID_EMPLE NUMBER(8,0) NOT NULL,
	NOMBRE VARCHAR2(50 BYTE),
	APELLIDOS VARCHAR2(100 BYTE),
	DNI VARCHAR2(10 BYTE),
	CONTRA VARCHAR2(50 BYTE) NOT NULL,
	BORRADO NUMBER(1,0)
);

ALTER TABLE EMPLEADOS ADD CONSTRAINT PK_EMPLEADOS PRIMARY KEY (ID_EMPLE);

CREATE TABLE PRODUCTOS (
	ID_PRODUCTO NUMBER(8,0) NOT NULL,
	NOMBRE_PRODUCTO VARCHAR2(100 BYTE),
	TIPO1 VARCHAR2(50 BYTE),
	TIPO2 VARCHAR2(50 BYTE),
	STOCK NUMBER(6,0),
	PRECIO NUMBER(6,2),
	BORRADO NUMBER(1,0)
);

ALTER TABLE PRODUCTOS ADD CONSTRAINT PK_PRODUCTOS PRIMARY KEY (ID_PRODUCTO);

CREATE TABLE FORMAS_PAGO (
	ID_FPAGO NUMBER(8,0) NOT NULL,
	FORMA_PAGO VARCHAR2(50 BYTE)
);

ALTER TABLE FORMAS_PAGO ADD CONSTRAINT PK_FORMAS_PAGO PRIMARY KEY (ID_FPAGO);

CREATE TABLE MESAS (
	ID_MESA NUMBER(8,0) NOT NULL,
	DESCIPCION_MESA VARCHAR2(50 BYTE),
	LIBRE NUMBER (1,0)
);

ALTER TABLE MESAS ADD CONSTRAINT PK_MESAS PRIMARY KEY (ID_MESA);

CREATE TABLE FACTURAS (
	ID_FACTURA NUMBER(8,0) NOT NULL,
	FECHA_FACTURA DATE,
	REF_MESA NUMBER(8,0) NULL,
	TOTAL NUMBER(8,2),
	TOTAL_IVA NUMBER(8,2)
);

ALTER TABLE FACTURAS ADD CONSTRAINT PK_FACTURAS PRIMARY KEY (ID_FACTURA);

CREATE TABLE PEDIDOS (
	ID_PEDIDO NUMBER(8,0) NOT NULL,
	REF_EMPLE NUMBER(8,0) NOT NULL,
	REF_MESA NUMBER(8,0) NULL,
	REF_PAGO NUMBER(8,0) NULL,
	TOTAL NUMBER (8,2),
	PAGADO NUMBER (1,0),
	FACTURADO NUMBER(1,0),
	FECHA_PEDIDO DATE
);

ALTER TABLE PEDIDOS ADD CONSTRAINT PK_PEDIDOS PRIMARY KEY (ID_PEDIDO);
ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS_EMPLE FOREIGN KEY (REF_EMPLE) REFERENCES EMPLEADOS(ID_EMPLE);
ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS_MESA FOREIGN KEY (REF_MESA) REFERENCES MESAS(ID_MESA);
ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS_PAGO FOREIGN KEY (REF_PAGO) REFERENCES FORMAS_PAGO(ID_FPAGO);

CREATE TABLE PEDIDOS_RRODUCTOS (
	ID_PEDIDO_PRODUC NUMBER(8,0) NOT NULL,
	REF_PEDIDO NUMBER(8,0) NOT NULL,
	REF_PRODUCTO NUMBER(8,0) NOT NULL,
	CANTIDAD NUMBER(4,0),
	PRECIO NUMBER(6,2)
);

ALTER TABLE PEDIDOS_RRODUCTOS ADD CONSTRAINT PK_PEDIDOS_RRODUCTOS PRIMARY KEY (ID_PEDIDO_PRODUC);
ALTER TABLE PEDIDOS_RRODUCTOS ADD CONSTRAINT FK_PEDIDPRODUC_PEDID FOREIGN KEY (REF_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO);
ALTER TABLE PEDIDOS_RRODUCTOS ADD CONSTRAINT FK_PEDIDPRODUC_PRODUC FOREIGN KEY (REF_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO);

CREATE TABLE PEDIDOS_FACTURAS (
	ID_PEDIDO_FACTURA NUMBER(8,0) NOT NULL,
	REF_PEDIDO NUMBER(8,0) NOT NULL,
	REF_FACTURA NUMBER(8,0) NOT NULL
);

ALTER TABLE PEDIDOS_FACTURAS ADD CONSTRAINT PK_PEDIDOS_FACTURAS PRIMARY KEY (ID_PEDIDO_FACTURA);
ALTER TABLE PEDIDOS_FACTURAS ADD CONSTRAINT FK_PEDIDFACT_PEDID FOREIGN KEY (REF_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO);
ALTER TABLE PEDIDOS_FACTURAS ADD CONSTRAINT FK_PEDIDFACT_FACTUR FOREIGN KEY (REF_FACTURA) REFERENCES FACTURAS(ID_FACTURA);